Type aafont
    Field Field0%
    Field Field1%
    Field Field2%[128]
    Field Field3%[128]
    Field Field4%[128]
    Field Field5%[128]
    Field Field6%
    Field Field7%
    Field Field8%
    Field Field9%
    Field Field10%
End Type
